package com.aykhedma.model.notification;

public enum NotificationType {
    EMERGENCY_OFFER,
    PROVIDER_SELECTED,
    BOOKING_REQUEST,
    STATUS_UPDATE,
    SYSTEM_ALERT,
    BOOKING_CONFIRMATION,
    BOOKING_REMINDER,
    BOOKING_CANCELLED,
    BOOKING_COMPLETED,
    REVIEW_RECEIVED,
    NEW_MESSAGE,
    PROVIDER_ACCEPTED,
    PROVIDER_REJECTED,
    ACCOUNT_UPDATE,
    PASSWORD_CHANGED,
    LOCATION_UPDATE,
    EMERGENCY_ALERT
}