package com.aykhedma.model.chat;

public enum ChatResponseType {
    TEXT,
    SUGGESTION,
    PROVIDER_LIST,
    AVAILABLE_SLOTS,
    BOOKING_CREATED,
    BOOKING_REDIRECT,
    PROVIDER_DETAILS,
    CLARIFICATION,
    EMERGENCY_CREATED,
    EMERGENCY_STATUS,
    EMERGENCY_PROVIDERS,
    ERROR
}